import type { Product, ProductCategory } from "@/lib/types"

const cigarettes: Product[] = [
  {
    id: "cig-zhonghua-hard",
    category: "cigarette",
    brand: "中华",
    series: "经典",
    nameZh: "中华（硬）",
    nameEn: "Zhonghua Classic Hard Pack",
    origin: "上海",
    priceCny: 45,
    kind: "烤烟",
    tarMg: 11,
    nicotineMg: 1.1,
    pack: "硬盒",
    notes: "香气醇厚、烟气细腻，带轻微坚果与烘焙甜感，收口干净。",
    tags: ["经典", "醇厚", "商务"],
  },
  {
    id: "cig-zhonghua-soft",
    category: "cigarette",
    brand: "中华",
    series: "经典",
    nameZh: "中华（软）",
    nameEn: "Zhonghua Soft Pack",
    origin: "上海",
    priceCny: 70,
    kind: "烤烟",
    tarMg: 11,
    nicotineMg: 1.1,
    pack: "软包",
    notes: "更柔和的焦甜与花香，烟气绵密，适合慢品。",
    tags: ["软包", "绵柔", "礼赠"],
  },
  {
    id: "cig-yuxi-soft",
    category: "cigarette",
    brand: "玉溪",
    series: "经典",
    nameZh: "玉溪（软）",
    nameEn: "Yuxi Soft",
    origin: "云南",
    priceCny: 23,
    kind: "烤烟",
    tarMg: 11,
    nicotineMg: 1.0,
    pack: "软包",
    notes: "烟草本香突出，层次平衡，带淡淡果甜与木质回甘。",
    tags: ["云南烟叶", "顺滑", "经典"],
  },
  {
    id: "cig-huanghelou-1916",
    category: "cigarette",
    brand: "黄鹤楼",
    series: "1916",
    nameZh: "黄鹤楼（1916）",
    nameEn: "Yellow Crane Tower 1916",
    origin: "湖北",
    priceCny: 100,
    kind: "烤烟",
    tarMg: 10,
    nicotineMg: 1.0,
    pack: "硬盒",
    notes: "香气飘逸，花蜜与烘烤坚果感交织，烟气细软，余味甘润。",
    tags: ["高端", "花香", "细软"],
  },
  {
    id: "cig-furongwang-hard",
    category: "cigarette",
    brand: "芙蓉王",
    series: "硬",
    nameZh: "芙蓉王（硬）",
    nameEn: "Furongwang Hard",
    origin: "湖南",
    priceCny: 25,
    kind: "烤烟",
    tarMg: 11,
    nicotineMg: 1.0,
    pack: "硬盒",
    notes: "烟气饱满，香甜与木质感明显，劲道适中。",
    tags: ["口粮", "饱满", "香甜"],
  },
  {
    id: "cig-liqun-hard",
    category: "cigarette",
    brand: "利群",
    series: "硬",
    nameZh: "利群（硬）",
    nameEn: "Liqun Hard",
    origin: "浙江",
    priceCny: 16,
    kind: "烤烟",
    tarMg: 11,
    nicotineMg: 1.0,
    pack: "硬盒",
    notes: "香气纯净，入口顺，尾段略带淡淡焦甜。",
    tags: ["清爽", "顺口", "经典"],
  },
  {
    id: "cig-hongtashan-classic",
    category: "cigarette",
    brand: "红塔山",
    series: "经典",
    nameZh: "红塔山（经典）",
    nameEn: "Hongtashan Classic",
    origin: "云南",
    priceCny: 10,
    kind: "烤烟",
    tarMg: 10,
    nicotineMg: 0.9,
    pack: "硬盒",
    notes: "烟草香突出，回味略甜，适合日常。",
    tags: ["性价比", "云南", "口粮"],
  },
  {
    id: "cig-yunyan-soft",
    category: "cigarette",
    brand: "云烟",
    series: "软珍品",
    nameZh: "云烟（软珍品）",
    nameEn: "Yunyan Soft Premium",
    origin: "云南",
    priceCny: 23,
    kind: "烤烟",
    tarMg: 10,
    nicotineMg: 1.0,
    pack: "软包",
    notes: "甜香明显，烟气细腻，带轻微花果气息。",
    tags: ["甜香", "细腻", "珍品"],
  },
  {
    id: "cig-baisha-hedao",
    category: "cigarette",
    brand: "白沙",
    series: "和天下",
    nameZh: "白沙（和天下）",
    nameEn: "Baisha Hetianxia",
    origin: "湖南",
    priceCny: 100,
    kind: "烤烟",
    tarMg: 10,
    nicotineMg: 1.0,
    pack: "硬盒",
    notes: "香气细雅，烟气绵柔，层次丰富，余味干净。",
    tags: ["高端", "绵柔", "雅香"],
  },
  {
    id: "cig-jiaozi-kx",
    category: "cigarette",
    brand: "娇子",
    series: "宽窄",
    nameZh: "娇子（宽窄）",
    nameEn: "Jiaozi Kuanzhai",
    origin: "四川",
    priceCny: 50,
    kind: "烤烟",
    tarMg: 10,
    nicotineMg: 1.0,
    pack: "硬盒",
    notes: "香气饱满且干净，带淡淡草本与甜香，口感均衡。",
    tags: ["均衡", "草本", "质感"],
  },
  {
    id: "cig-taishan-classic",
    category: "cigarette",
    brand: "泰山",
    series: "经典",
    nameZh: "泰山（经典）",
    nameEn: "Taishan Classic",
    origin: "山东",
    priceCny: 12,
    kind: "烤烟",
    tarMg: 11,
    nicotineMg: 1.0,
    pack: "硬盒",
    notes: "入口顺，烟香厚实，后段略带焦甜。",
    tags: ["厚实", "口粮", "经典"],
  },
  {
    id: "cig-hongshuangxi-classic",
    category: "cigarette",
    brand: "红双喜",
    series: "经典",
    nameZh: "红双喜（经典）",
    nameEn: "Double Happiness Classic",
    origin: "上海",
    priceCny: 12,
    kind: "烤烟",
    tarMg: 12,
    nicotineMg: 1.1,
    pack: "硬盒",
    notes: "烟气偏厚，香气直接，适合偏重口味用户。",
    tags: ["劲道", "经典", "直给"],
  },
  {
    id: "cig-nanjing-yupin",
    category: "cigarette",
    brand: "南京",
    series: "雨花石",
    nameZh: "南京（雨花石）",
    nameEn: "Nanjing Yuhuashi",
    origin: "江苏",
    priceCny: 55,
    kind: "中支",
    tarMg: 8,
    nicotineMg: 0.8,
    pack: "硬盒",
    notes: "香气细致偏清雅，烟气柔，留香长。",
    tags: ["清雅", "中支", "留香"],
  },
  {
    id: "cig-suyan-classic",
    category: "cigarette",
    brand: "苏烟",
    series: "经典",
    nameZh: "苏烟（软金砂）",
    nameEn: "Suyan Soft Gold",
    origin: "江苏",
    priceCny: 48,
    kind: "烤烟",
    tarMg: 10,
    nicotineMg: 1.0,
    pack: "软包",
    notes: "香气细腻，焦甜与木香协调，烟气绵长。",
    tags: ["细腻", "焦甜", "软包"],
  },
  {
    id: "cig-zhangjiakou-hetao",
    category: "cigarette",
    brand: "荷花",
    series: "经典",
    nameZh: "荷花（经典）",
    nameEn: "Hehua Classic",
    origin: "河北",
    priceCny: 55,
    kind: "细支",
    tarMg: 8,
    nicotineMg: 0.8,
    pack: "硬盒",
    notes: "清香偏甜，烟气轻柔，适合偏淡口感。",
    tags: ["细支", "清香", "轻柔"],
  },
  {
    id: "cig-pearl-river",
    category: "cigarette",
    brand: "珠江",
    series: "经典",
    nameZh: "珠江（经典）",
    nameEn: "Pearl River Classic",
    origin: "广东",
    priceCny: 10,
    kind: "烤烟",
    tarMg: 11,
    nicotineMg: 1.0,
    pack: "硬盒",
    notes: "香气朴实，入口顺，余味略甜。",
    tags: ["朴实", "口粮", "顺口"],
  },
  {
    id: "cig-zhenlong",
    category: "cigarette",
    brand: "真龙",
    series: "经典",
    nameZh: "真龙（经典）",
    nameEn: "Zhenlong Classic",
    origin: "广西",
    priceCny: 13,
    kind: "烤烟",
    tarMg: 11,
    nicotineMg: 1.0,
    pack: "硬盒",
    notes: "香气略带草木感，回味干净。",
    tags: ["清爽", "草木", "干净"],
  },
  {
    id: "cig-dongfanghong",
    category: "cigarette",
    brand: "东方红",
    series: "经典",
    nameZh: "东方红（经典）",
    nameEn: "Dongfanghong Classic",
    origin: "河南",
    priceCny: 12,
    kind: "烤烟",
    tarMg: 11,
    nicotineMg: 1.0,
    pack: "硬盒",
    notes: "烟香直接，略带焦甜，适合重口用户。",
    tags: ["劲道", "焦甜", "经典"],
  },
  {
    id: "cig-chunghwa-mint",
    category: "cigarette",
    brand: "中南海",
    series: "薄荷",
    nameZh: "中南海（薄荷）",
    nameEn: "Zhongnanhai Mint",
    origin: "北京",
    priceCny: 14,
    kind: "薄荷",
    tarMg: 6,
    nicotineMg: 0.6,
    pack: "硬盒",
    notes: "清凉薄荷感明显，烟气偏轻，适合清爽路线。",
    tags: ["薄荷", "清凉", "淡口"],
  },
  {
    id: "cig-lotus-pearl",
    category: "cigarette",
    brand: "牡丹",
    series: "经典",
    nameZh: "牡丹（经典）",
    nameEn: "Mudan Classic",
    origin: "上海",
    priceCny: 13,
    kind: "烤烟",
    tarMg: 11,
    nicotineMg: 1.0,
    pack: "硬盒",
    notes: "烟气适中，香气偏甜，后段略带烘烤感。",
    tags: ["甜香", "怀旧", "经典"],
  },
  {
    id: "cig-yanjing-king",
    category: "cigarette",
    brand: "延安",
    series: "经典",
    nameZh: "延安（经典）",
    nameEn: "Yan'an Classic",
    origin: "陕西",
    priceCny: 11,
    kind: "烤烟",
    tarMg: 11,
    nicotineMg: 1.0,
    pack: "硬盒",
    notes: "烟香扎实，回味带一点坚果与焦香。",
    tags: ["扎实", "坚果", "焦香"],
  },
]

const cigars: Product[] = [
  {
    id: "cigar-changcheng-132",
    category: "cigar",
    brand: "长城",
    series: "132",
    nameZh: "长城（132）",
    nameEn: "Great Wall 132",
    origin: "四川",
    priceCny: 35,
    size: "127mm × 38RG",
    wrapper: "国产/混合",
    binder: "国产",
    filler: "国产",
    strength: "中",
    notes: "木香与烘焙甜感为主，烟气柔和，后段略有可可与坚果味。",
    tags: ["入门", "木香", "均衡"],
  },
  {
    id: "cigar-changcheng-legend",
    category: "cigar",
    brand: "长城",
    series: "传奇",
    nameZh: "长城（传奇）",
    nameEn: "Great Wall Legend",
    origin: "四川",
    priceCny: 60,
    size: "150mm × 50RG",
    wrapper: "进口茄衣",
    binder: "进口/混合",
    filler: "混合",
    strength: "中",
    notes: "香气更立体，奶油与香草气息明显，尾段带轻微胡椒。",
    tags: ["奶油", "香草", "更饱满"],
  },
  {
    id: "cigar-wangguan-vanilla",
    category: "cigar",
    brand: "王冠",
    series: "香草",
    nameZh: "王冠（香草）",
    nameEn: "Wangguan Vanilla",
    origin: "安徽",
    priceCny: 28,
    size: "110mm × 38RG",
    wrapper: "国产",
    binder: "国产",
    filler: "国产",
    strength: "淡",
    notes: "香草甜香突出，适合轻口味与新手。",
    tags: ["香草", "淡", "甜香"],
  },
  {
    id: "cigar-wangguan-classic",
    category: "cigar",
    brand: "王冠",
    series: "经典",
    nameZh: "王冠（经典）",
    nameEn: "Wangguan Classic",
    origin: "安徽",
    priceCny: 30,
    size: "120mm × 40RG",
    wrapper: "国产",
    binder: "国产",
    filler: "国产",
    strength: "中",
    notes: "烟草本味清晰，带木质与淡可可香。",
    tags: ["本味", "木香", "可可"],
  },
  {
    id: "cigar-huanghelou-cigar",
    category: "cigar",
    brand: "黄鹤楼",
    series: "雪茄",
    nameZh: "黄鹤楼（雪之景）",
    nameEn: "Yellow Crane Tower Cigar",
    origin: "湖北",
    priceCny: 45,
    size: "115mm × 42RG",
    wrapper: "进口茄衣",
    binder: "混合",
    filler: "混合",
    strength: "中",
    notes: "花香与木香交织，烟气细柔，余味略甜。",
    tags: ["花香", "细柔", "甜回甘"],
  },
  {
    id: "cigar-taishan-cigar",
    category: "cigar",
    brand: "泰山",
    series: "雪茄",
    nameZh: "泰山（雪茄）",
    nameEn: "Taishan Cigar",
    origin: "山东",
    priceCny: 25,
    size: "100mm × 36RG",
    wrapper: "国产",
    binder: "国产",
    filler: "国产",
    strength: "淡",
    notes: "清淡易抽，木香轻柔，适合日常小雪茄。",
    tags: ["小雪茄", "淡", "日常"],
  },
  {
    id: "cigar-changcheng-mini",
    category: "cigar",
    brand: "长城",
    series: "迷你",
    nameZh: "长城（迷你）",
    nameEn: "Great Wall Mini",
    origin: "四川",
    priceCny: 18,
    size: "90mm × 26RG",
    wrapper: "国产",
    binder: "国产",
    filler: "国产",
    strength: "淡",
    notes: "短时体验，香气清爽，适合随手一支。",
    tags: ["迷你", "短时", "清爽"],
  },
  {
    id: "cigar-wangguan-sumatra",
    category: "cigar",
    brand: "王冠",
    series: "苏门答腊",
    nameZh: "王冠（苏门答腊）",
    nameEn: "Wangguan Sumatra",
    origin: "安徽",
    priceCny: 38,
    size: "130mm × 46RG",
    wrapper: "苏门答腊茄衣",
    binder: "混合",
    filler: "混合",
    strength: "中",
    notes: "坚果与烘焙香明显，尾段带轻微香料感。",
    tags: ["坚果", "烘焙", "香料"],
  },
  {
    id: "cigar-changcheng-glory",
    category: "cigar",
    brand: "长城",
    series: "国礼",
    nameZh: "长城（国礼）",
    nameEn: "Great Wall Guoli",
    origin: "四川",
    priceCny: 120,
    size: "156mm × 52RG",
    wrapper: "进口茄衣",
    binder: "进口/混合",
    filler: "混合",
    strength: "浓",
    notes: "烟气厚重、香气集中，带黑巧、皮革与胡椒，尾段力量感明显。",
    tags: ["浓", "皮革", "黑巧"],
  },
  {
    id: "cigar-huanghelou-harmony",
    category: "cigar",
    brand: "黄鹤楼",
    series: "和韵",
    nameZh: "黄鹤楼（和韵）",
    nameEn: "Yellow Crane Tower Harmony",
    origin: "湖北",
    priceCny: 55,
    size: "140mm × 48RG",
    wrapper: "进口茄衣",
    binder: "混合",
    filler: "混合",
    strength: "中",
    notes: "木香、花香与奶油感平衡，烟气细腻，尾段微甜。",
    tags: ["平衡", "奶油", "花香"],
  },
]

const ecigs: Product[] = [
  {
    id: "ecig-relx-infinity2",
    category: "ecig",
    brand: "RELX 悦刻",
    series: "幻影",
    nameZh: "悦刻（幻影）",
    nameEn: "RELX Infinity",
    origin: "深圳",
    priceCny: 299,
    deviceType: "换弹式",
    batteryMah: 380,
    liquidMl: 1.9,
    nicotinePercent: 3,
    flavors: ["冰镇西瓜", "经典烟草", "冰爽薄荷", "绿豆冰"],
    features: ["磁吸换弹", "轻震提醒", "防漏油结构"],
    notes: "口感顺滑，雾化细腻，击喉感中等，适合口味多变用户。",
    tags: ["换弹", "顺滑", "主流"],
  },
  {
    id: "ecig-yooz-mini",
    category: "ecig",
    brand: "YOOZ 柚子",
    series: "Mini",
    nameZh: "柚子（Mini）",
    nameEn: "YOOZ Mini",
    origin: "深圳",
    priceCny: 199,
    deviceType: "换弹式",
    batteryMah: 350,
    liquidMl: 2.0,
    nicotinePercent: 3,
    flavors: ["冰葡萄", "百香果", "薄荷", "经典烟草"],
    features: ["轻巧便携", "Type-C 充电", "口数稳定"],
    notes: "雾量适中，甜感明显，适合果味偏好。",
    tags: ["果味", "轻巧", "换弹"],
  },
  {
    id: "ecig-moti-s",
    category: "ecig",
    brand: "MOTI 魔笛",
    series: "S",
    nameZh: "魔笛（S）",
    nameEn: "MOTI S",
    origin: "深圳",
    priceCny: 239,
    deviceType: "换弹式",
    batteryMah: 400,
    liquidMl: 2.0,
    nicotinePercent: 3,
    flavors: ["冰咖啡", "冰薄荷", "蜜桃乌龙", "荔枝冰"],
    features: ["雾化温控", "顺滑口感", "更强续航"],
    notes: "香气扩散更强，适合追求浓郁风味的人。",
    tags: ["浓郁", "温控", "换弹"],
  },
  {
    id: "ecig-snowplus-lite",
    category: "ecig",
    brand: "SnowPlus 雪加",
    series: "Lite",
    nameZh: "雪加（Lite）",
    nameEn: "SnowPlus Lite",
    origin: "深圳",
    priceCny: 189,
    deviceType: "换弹式",
    batteryMah: 360,
    liquidMl: 2.0,
    nicotinePercent: 3,
    flavors: ["老冰棍", "青提", "薄荷", "冰柠檬茶"],
    features: ["轻薄机身", "磁吸换弹", "入口柔和"],
    notes: "整体偏柔和，适合轻口与长时间使用。",
    tags: ["轻口", "轻薄", "换弹"],
  },
  {
    id: "ecig-lami-one",
    category: "ecig",
    brand: "LAMI 徕米",
    series: "ONE",
    nameZh: "徕米（ONE）",
    nameEn: "LAMI ONE",
    origin: "深圳",
    priceCny: 169,
    deviceType: "换弹式",
    batteryMah: 380,
    liquidMl: 2.0,
    nicotinePercent: 3,
    flavors: ["冰可乐", "冰西瓜", "薄荷", "草莓奶昔"],
    features: ["防漏设计", "稳定雾化", "轻巧握感"],
    notes: "甜感饱满，适合偏甜口味。",
    tags: ["甜口", "稳定", "换弹"],
  },
  {
    id: "ecig-vtv-disposable",
    category: "ecig",
    brand: "VTV",
    series: "一次性",
    nameZh: "VTV（一次性）",
    nameEn: "VTV Disposable",
    origin: "深圳",
    priceCny: 59,
    deviceType: "一次性",
    batteryMah: 500,
    liquidMl: 6.0,
    nicotinePercent: 2,
    flavors: ["冰葡萄", "冰薄荷", "芒果冰", "青柠苏打"],
    features: ["开盒即用", "雾量更大", "口数充足"],
    notes: "方便省心，口味浓，适合短期出行。",
    tags: ["一次性", "大雾量", "便携"],
  },
  {
    id: "ecig-feelife-open",
    category: "ecig",
    brand: "FEELM 飞雾",
    series: "开放式",
    nameZh: "飞雾（开放式）",
    nameEn: "FEELM Open",
    origin: "深圳",
    priceCny: 399,
    deviceType: "开放式",
    batteryMah: 900,
    liquidMl: 4.0,
    nicotinePercent: 0,
    flavors: ["自选烟油"],
    features: ["功率可调", "可更换雾化芯", "进阶玩法"],
    notes: "可玩性更强，适合进阶用户。",
    tags: ["开放式", "可调", "进阶"],
  },
  {
    id: "ecig-relx-disposable",
    category: "ecig",
    brand: "RELX 悦刻",
    series: "轻风",
    nameZh: "悦刻（轻风一次性）",
    nameEn: "RELX Disposable",
    origin: "深圳",
    priceCny: 79,
    deviceType: "一次性",
    batteryMah: 550,
    liquidMl: 6.0,
    nicotinePercent: 2,
    flavors: ["冰薄荷", "乌龙茶", "冰葡萄", "柠檬气泡"],
    features: ["开盒即用", "更稳口感", "外出友好"],
    notes: "适合备用机与出行场景。",
    tags: ["一次性", "备用", "外出"],
  },
  {
    id: "ecig-yooz-disposable",
    category: "ecig",
    brand: "YOOZ 柚子",
    series: "Go",
    nameZh: "柚子（Go 一次性）",
    nameEn: "YOOZ Go",
    origin: "深圳",
    priceCny: 69,
    deviceType: "一次性",
    batteryMah: 520,
    liquidMl: 5.5,
    nicotinePercent: 2,
    flavors: ["冰西瓜", "青提", "薄荷", "芒果冰"],
    features: ["轻便", "雾量适中", "口味偏甜"],
    notes: "甜口果味更突出，口感清爽。",
    tags: ["一次性", "果味", "清爽"],
  },
  {
    id: "ecig-moti-disposable",
    category: "ecig",
    brand: "MOTI 魔笛",
    series: "Go 一次性",
    nameZh: "魔笛（Go 一次性）",
    nameEn: "MOTI Go",
    origin: "深圳",
    priceCny: 75,
    deviceType: "一次性",
    batteryMah: 600,
    liquidMl: 6.5,
    nicotinePercent: 2,
    flavors: ["冰咖啡", "冰薄荷", "蓝莓", "青柠"],
    features: ["雾量更足", "口味更浓", "即用即走"],
    notes: "更偏浓郁路线，适合追求击喉的人。",
    tags: ["一次性", "浓郁", "击喉"],
  },
]

export const PRODUCTS: Product[] = [...cigarettes, ...cigars, ...ecigs]

export function getProductById(id: string) {
  return PRODUCTS.find((p) => p.id === id) ?? null
}

export function getCategoryLabel(category: ProductCategory) {
  if (category === "cigarette") return "卷烟"
  if (category === "cigar") return "雪茄"
  return "电子烟"
}

